title:
  base-length: 15
  longer-length: 20

elytra-drop-chance: 0.2
  
bans-broadcast:
  channel: bans-mutes-test
  allowed:
    - muted
    - warned
    - warned.offline
    - broadcast

disable-chorus-tp: true