name: Ukutils
version: '${version}'
main: net.uku3lig.ukutils.Ukutils
api-version: 1.17
depend: [ LuckPerms, VentureChat, LiteBans ]
authors: [ uku ]
description: a few utility commands
commands:
  color:
    description: Change the color of your username
    usage: /color [user] <color>
    permission: ukutils.color
  title:
    description: Give yourself a title (max 15 chars)
    usage: /title [user] <text>
    permission: ukutils.title
  boat:
    description: Spawns a boat
    usage: /boat
    permission: ukutils.boat
  nether:
    description: Sends you to the nether
    usage: /nether
    permission: ukutils.nether
  end:
    description: Sends you to the end
    usage: /end
    permission: ukutils.end
  toggletimber:
    aliases: [ toggletreefeller ]
    description: Toggles tree feller
    usage: /toggletimber
    permission: ukutils.toggletimber
  enderchest:
    aliases: [ ec ]
    description: Opens your enderchest
    usage: /enderchest [player]
    permission: ukutils.ec
  killboats:
    description: Kills all empty boats
    usage: /killboats
    permission: ukutils.killboats
  shrug:
    description: ¯\_(ツ)_/¯
    usage: /shrug
    permission: ukutils.shrug
permissions:
  ukutils.color.rgb:
    description: allows use of rgb color codes
  ukutils.color.others:
    description: allow to change other users' colors
  ukutils.title.longer:
    description: allows for a longer title (20 chars)
  ukutils.title.others:
    description: allows to change others' title
  ukutils.ec.others:
    description: allows you to see others' enderchests
  ukutils.elytra:
    description: allows you to renew elytras
