name: Ukutils
version: '${version}'
main: net.uku3lig.ukutils.Ukutils
api-version: 1.17
depend: [ LuckPerms, VentureChat ]
authors: [ uku ]
description: a few utility commands
commands:
  color:
    description: Change the color of your username
    usage: /color [user] <color>
    permission: ukutils.color
  title:
    description: Give yourself a title (max 15 chars)
    usage: /title [user] <text>
    permission: ukutils.title
  boat:
    description: Spawns a boat
    usage: /boat
    permission: ukutils.boat
permissions:
  ukutils.color.rgb:
    description: allows use of rgb color codes
  ukutils.color.others:
    description: allow to change other users' colors
  ukutils.title.longer:
    description: allows for a longer title (20 chars)
  ukutils.title.others:
    description: allows to change others' title
